export default [
    {
        id: 1,
        imageUrl: "https://source.unsplash.com/WLxQvbMyfas",
        // imageLocation1: "./img/location-logo-pic.png",
        location: "JAPAN",
        mapLink: "https://goo.gl/maps/9VfNQXRzTUgECA5D6",
        mapText: "View on Google Maps",
        title: "Mount Fuji",
        startDate: "12 Jan, 2021",
        endDate: "24 Jan, 2021",
        description: "Mount Fuji is the tallest mountain in Japan, standing at 3,776 meters (12,380 feet). Mount Fuji is the single most popular tourist site in Japan, for both Japanese and foreign tourists.",
        imageLocation: "../../public/img/location-logo.svg",
    },
    {
        id: 2,
        imageUrl: "https://source.unsplash.com/JmuyB_LibRo",
        // imageLocation1: "./img/location-logo-pic.png",
        location: "AUSTRALIA",
        mapLink: "https://goo.gl/maps/kv233twx2fESSrPL8",
        mapText: "View on Google Maps",
        title: "Sydney Opera House",
        startDate: "27 May, 2021",
        endDate: "8 Jun, 2021",
        description: "The Sydney Opera House is a multi-venue performing arts centre in Sydney. Located on the banks of the Sydney Harbour, it is often regarded as one of the 20th century's most famous and distinctive buildings.",
        imageLocation: "../../public/img/location-logo.svg",
    },
    {
        id: 3,
        imageUrl: "https://source.unsplash.com/3PeSjpLVtLg",
        // imageLocation1: "./img/location-logo-pic.png",
        location: "NORWAY",
        mapLink: "https://goo.gl/maps/YSZbB255fptNcD2F9",
        mapText: "View on Google Maps",
        title: "Geirangerfjord",
        startDate: "01 Oct, 2021",
        endDate: "18 Nov, 2021",
        description: "The Geiranger Fjord is a fjord in the Sunnmøre region of Møre og Romsdal county, Norway. It is located entirely in the Stranda Municipality.",
        imageLocation: "../../public/img/location-logo.svg",
    }
]